services:
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -dev -client 0.0.0.0 -ui"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8500/v1/status/leader" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      CONSUL_BIND_INTERFACE: eth0
    networks:
      - board-project
    restart: always

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    ports:
      - "9999:9999"
      - "9998:9998"
    environment:
      FABIO_REGISTRY_CONSUL_ADDR: "consul:8500"
    depends_on:
      consul:
        condition: service_healthy
    networks:
      - board-project

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    depends_on:
      consul:
        condition: service_healthy
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - board-project

  board-project-1:
    container_name: board-project-container
    image: ghcr.io/ttodoshi/board-project:latest
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      PORT: 8080
      PROFILE: "dev"# dev, prod
      LOG_LEVEL: "debug"#trace, debug, info, warn, error
      REDIS_ADDR: "redis:6379"
      CONSUL_HOST: "consul:8500"
      CONSUL_SERVICE_NAME: "board-project"
      CONSUL_SERVICE_ADDRESS: "board-project-1"
      CONSUL_TAGS: "urlprefix-/api/v1"
    networks:
      - board-project

#  board-project-2:
#    container_name: board-project-container
#    image: ghcr.io/ttodoshi/board-project:latest
#    ports:
#      - "8090:8090"
#    depends_on:
#      redis:
#        condition: service_healthy
#    environment:
#      PORT: 8090
#      PROFILE: "dev"# dev, prod
#      LOG_LEVEL: "debug"#trace, debug, info, warn, error
#      REDIS_ADDR: "redis:6379"
#      CONSUL_HOST: "consul:8500"
#      CONSUL_SERVICE_NAME: "board-project"
#      CONSUL_SERVICE_ADDRESS: "board-project-2"
#      CONSUL_TAGS: "urlprefix-/api/v1"
#    networks:
#      - board-project

networks:
  board-project:
    driver: bridge

volumes:
  redis:
